# remote_theme: jekyll/minima
# remote_theme: benbalter/retlab
# remote_theme: "mmistakes/minimal-mistakes@4.19.3"
# remote_theme: murraco/jekyll-theme-minimal-resume
# remote_theme: aksakalli/jekyll-doc-theme@gh-pages
# remote_theme: "mmistakes/jekyll-theme-basically-basic"
remote_theme: "mmistakes/so-simple-theme@3.2.0"

# remote_theme: kitian616/jekyll-TeXt-theme
# remote_theme: CloudCannon/frisco-jekyll-template

title: Dance-AI Project
description: Welcome, this is Dance-AI website.

plugins:
  - jekyll-include-cache
